# Generated by Django 6.0.7 on 2026-08-05 16:19

import desembaralha.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=desembaralha.models.gerar_codigo, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando jogadores'), ('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada')], default='aguardando', max_length=15)),
                ('fase_atual', models.PositiveSmallIntegerField(default=0)),
                ('nivel_atual', models.CharField(choices=[('facil', 'facil'), ('medio', 'medio'), ('dificil', 'dificil')], default='facil', max_length=10)),
                ('max_jogadores', models.PositiveSmallIntegerField(default=8)),
                ('host_session_key', models.CharField(max_length=40)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False)),
                ('pontos_totais', models.PositiveIntegerField(default=0)),
                ('ordem_eliminacao', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('entrou_em', models.DateTimeField(auto_now_add=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_desembaralha', to='hub.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='desembaralha.partida')),
            ],
            options={
                'unique_together': {('partida', 'jogador')},
            },
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.PositiveSmallIntegerField()),
                ('sequencia', models.PositiveSmallIntegerField(default=0)),
                ('nivel', models.CharField(choices=[('facil', 'facil'), ('medio', 'medio'), ('dificil', 'dificil')], max_length=10)),
                ('duracao_segundos', models.PositiveSmallIntegerField()),
                ('desempate', models.BooleanField(default=False)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('encerrada', models.BooleanField(default=False)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodadas', to='desembaralha.partida')),
            ],
            options={
                'ordering': ['fase', 'sequencia'],
                'unique_together': {('partida', 'fase', 'sequencia')},
            },
        ),
        migrations.CreateModel(
            name='QuadroJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila_palavras', models.JSONField()),
                ('indice_atual', models.PositiveSmallIntegerField(default=0)),
                ('resolvidas', models.JSONField(blank=True, default=list)),
                ('pontos_rodada', models.PositiveIntegerField(default=0)),
                ('acertos', models.PositiveSmallIntegerField(default=0)),
                ('erros', models.PositiveSmallIntegerField(default=0)),
                ('terminou_em', models.DateTimeField(blank=True, null=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadros', to='desembaralha.participante')),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadros', to='desembaralha.rodada')),
            ],
            options={
                'unique_together': {('rodada', 'participante')},
            },
        ),
    ]
