# Generated by Django 6.0.7 on 2026-08-03 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacapalavras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rodada',
            options={'ordering': ['fase', 'sequencia']},
        ),
        migrations.AlterUniqueTogether(
            name='rodada',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rodada',
            name='desempate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rodada',
            name='sequencia',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='rodada',
            unique_together={('partida', 'fase', 'sequencia')},
        ),
        migrations.CreateModel(
            name='PalavraParaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra_ascii', models.CharField(max_length=20)),
                ('celulas', models.JSONField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('avaliada_em', models.DateTimeField(blank=True, null=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palavras_para_avaliacao', to='cacapalavras.participante')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palavras_para_avaliacao', to='cacapalavras.partida')),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palavras_para_avaliacao', to='cacapalavras.rodada')),
            ],
            options={
                'verbose_name': 'Palavra para avaliação',
                'verbose_name_plural': 'Palavras para avaliação',
                'unique_together': {('rodada', 'participante', 'palavra_ascii')},
            },
        ),
    ]
