# Generated by Django 6.0.7 on 2026-08-03 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=30)),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trofeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('cacapalavras', 'Caça-Palavras'), ('desembaralha', 'Desembaralha'), ('forca', 'Forca'), ('jogodavelha', 'Jogo da Velha'), ('ligmix', 'LigMix'), ('multiplex', 'Multiplex'), ('palavrascruzadas', 'Palavras Cruzadas'), ('somamais', 'SomaMais')], max_length=20)),
                ('conquistado_em', models.DateTimeField(auto_now_add=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trofeus', to='hub.jogador')),
            ],
        ),
    ]
